entity: asl4acl
project: asl4acl_mlp_signtype
program: deep_learning.train_main
command:
  - ${env}
  - ${interpreter}
  - '-m'
  - ${program}
  - ${args}
method: bayes
metric:
  name: val/mcc
  goal: maximize
parameters:
  model:
    value: "mlp"
  n_lin_layers:
    values: [2, 4, 8]
  hidden_dim:
    values: [1024, 2048, 4096]
  lin_dropout:
    min: 0.0
    max: 0.5
  epochs:
    value: 50
  batch_size:
    values: [512, 1024]
  optimizer:
    value: "adam"
  lr:
    min: 0.0001
    max: 0.1
  step_size:
    min: 10
    max: 50
  gamma:
    min: 0.1
    max: 0.5
  batch_norm:
    value: true
  seed:
    value: 13
  source:
    value: npy
  label:
    value: SignType
  tracker:
    value: "27-frank-frank"