Experiment_name: signtype-hrt

feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/final/signtype/27_2-hrt/train_data_joint_hrt.npy
  label_path: ./data/final/signtype/27_2-hrt/train_label_hrt.pkl
  debug: False
  random_choose: True
  window_size: 100
  random_shift: True
  normalization: True
  random_mirror: False
  random_mirror_p: 0.5
  is_vector: False

test_feeder_args:
  data_path: ./data/final/signtype/27_2-hrt/val_data_joint_hrt.npy
  label_path: ./data/final/signtype/27_2-hrt/val_label_hrt.pkl
  random_mirror: False
  normalization: True

model: model.decouple_gcn_attn.Model
model_args:
  num_class: 5
  num_point: 27
  in_channels: 3
  num_person: 1
  graph: graph.sign_27.Graph
  groups: 16
  block_size: 41
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [150, 200]

# training
device: [0]
keep_rate: 0.9
only_train_epoch: 1
batch_size: 64
test_batch_size: 64
num_epoch: 250
nesterov: True
warm_up_epoch: 20
label2id: ./data/final/signtype/27_2-hrt/label2id.json
