entity: asl4acl
project: asl4acl_rnn_majorlocation
program: deep_learning.train_main
command:
  - ${env}
  - ${interpreter}
  - '-m'
  - ${program}
  - ${args}
method: bayes
metric:
  name: val/mcc
  goal: maximize
parameters:
  model:
    values: ["lstm", "gru"]
  bidirectional:
    values: [true, false]
  n_layers:
    values: [1, 2, 3]
  n_lin_layers:
    values: [0, 1, 2]
  hidden_dim:
    values: [128, 512, 1024]
  dropout:
    min: 0.0
    max: 0.5
  lin_dropout:
    min: 0.0
    max: 0.5
  epochs:
    value: 50
  batch_size:
    values: [64, 128]
  optimizer:
    value: "adam"
  lr:
    min: 0.0001
    max: 0.1
  step_size:
    min: 10
    max: 50
  gamma:
    min: 0.1
    max: 0.5
  batch_norm:
    value: true
  seed:
    value: 13
  source:
    value: npy
  label:
    value: MajorLocation
  tracker:
    value: "27_2-hrt"