Experiment_name: test

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /data/asl/out/movement/7-frank-movement/movement_train_data_joint.npy
  label_path: /data/asl/out/movement/7-frank-movement/movement_train_label.pkl
  debug: False
  random_choose: True
  downsample: 3
  window_size: 33
  random_shift: True
  normalization: True
  random_mirror: False
  random_mirror_p: 0.5
  is_vector: False
  use_mmap: False

test_feeder_args:
  data_path: /data/asl/out/movement/7-frank-movement/movement_val_data_joint.npy
  label_path: /data/asl/out/movement/7-frank-movement/movement_val_label.pkl
  random_mirror: False
  debug: False
  normalization: True

# model
model: model.decouple_gcn_attn.Model
model_args:
  num_class: 6
  in_channels: 3
  num_point: 7
  num_person: 1
  graph: graph.sign_7_frank.Graph
  groups: 16
  block_size: 41
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [3, 4]

# training
device: [0]
keep_rate: 0.9
only_train_epoch: 1
batch_size: 128
test_batch_size: 64
num_epoch: 5
nesterov: True
warm_up_epoch: 20
cuda: False
