Experiment_name: test

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /data/asl/out/movement/27_2-hrt-zeropad/train_data_joint_hrt-zeropad.npy
  label_path: /data/asl/out/movement/27_2-hrt-zeropad/train_label_hrt-zeropad.pkl
  debug: True
  random_choose: True
  window_size: 100
  #downsample: 3
  random_shift: True
  normalization: True
  random_mirror: False
  random_mirror_p: 0.5
  is_vector: False

test_feeder_args:
  data_path: /data/asl/out/movement/27_2-hrt-zeropad/train_data_joint_hrt-zeropad.npy
  label_path: /data/asl/out/movement/27_2-hrt-zeropad/train_label_hrt-zeropad.pkl
  random_mirror: False
  debug: True
  normalization: True

# model
model: model.decouple_gcn_attn.Model
model_args:
  num_class: 6
  in_channels: 3
  num_point: 27
  num_person: 1
  graph: graph.sign_27.Graph
  groups: 16
  block_size: 41
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [3, 4]

# training
device: [0]
keep_rate: 0.9
only_train_epoch: 1
batch_size: 32
test_batch_size: 64
num_epoch: 5
nesterov: True
warm_up_epoch: 20
cuda: False
